languageCode = "en-us"
title = "Research Organization Registry (ROR)"
baseurl = "http://localhost:1313"
style = "turquoise"
theme = "hugo-ror"
pluralizelisttitles = "false"
summaryLength = 20

[params]
	date_format = "January 2, 2006"
	CSSVersion = 3
	description = 'The Research Organization Registry (ROR) is a global, community-led registry of open persistent identifiers for research organizations. ROR aims to provide a persistent identifier (PID) for every research organization in the world, just as ORCID provides persistent identifiers for researchers and DOIs provide persistent identifiers for research outputs. All ROR data is open on the web and public domain via CC0, and the ROR dataset and API are free to use.'
	title = 'Research Organization Registry (ROR)'
  	images = ['/img/ror-logo-800.png']
  	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[markup.tableOfContents]
   endLevel = 2
   ordered = false
   startLevel = 2     

[params.widgets]
    search = true
    categories = true
    tags = true

[params.carousel]
    enable = false

[params.landingbanner]
  enable = true
    image = "/img/ROR_Lions_Banner.jpg"
    text = ""
    textcolor = '#fff'

[params.blurb]
    enable = true

[params.announcement]
    enable = false 

[params.homepage_features]
    enable = true

[params.testimonials]
    enable = false

[params.socials]
    enable = true

[params.recent_posts]
    enable = true
    title = "News and Updates"

[params.twitter_feed]
    enable = false
    title = "Twitter Feed"
    
[params.social]
	twitter = 'ResearchOrgs' 
	
