name: Deploy Dev
on:
  push:
    branches:
      - "dev"
    paths-ignore:
      - '**README.md'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-hugo-sass

      - uses: ./.github/actions/build-hugo
        with:
          config: dev.toml

      - name: Deploy
        uses: ./.github/actions/deploy-s3
        with:
          bucket: ${{ secrets.S3_BUCKET_DEV }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}

      - name: Notify Slack
        if: always()
        uses: ./.github/actions/notify-slack
        with:
          site_url: https://dev.ror.org
          job_status: ${{ job.status }}
          workflow_name: ${{ github.workflow }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
