name: Deploy Master
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - '**README.md'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0

      - uses: ./.github/actions/setup-hugo-sass

      - uses: ./.github/actions/build-hugo
        with:
          config: live.toml

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true

  notify-slack:
    needs: run
    uses: ./.github/workflows/notify-slack.yml
    with:
      site_url: https://ror.org
      job_status: ${{ needs.run.result }}
      workflow_name: ${{ github.workflow }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
